awslabs/idf-modules

examples/manifests/example/example-modules.yaml, examples/manifests/example/networking-modules.yaml
Updating manifests to point to a pinned release version for examples
=> modifying manifests to refer to release

README.md
=> updating README to reflect repo name change

.github/workflows/main.yml, CHANGELOG.md, manifests/local/compute-modules.yaml, manifests/local/deployment.yaml, modules/compute/aws-batch/README.md, modules/compute/aws-batch/SEEDFARMER_MODULE_METADATA, modules/compute/aws-batch/app.py, modules/compute/aws-batch/cdk-exports.json, modules/compute/aws-batch/coverage.ini, modules/compute/aws-batch/deployspec.yaml, modules/compute/aws-batch/export_metadata.py, modules/compute/aws-batch/modulestack.yaml, modules/compute/aws-batch/pyproject.toml, modules/compute/aws-batch/requirements.txt, modules/compute/aws-batch/setup.cfg, modules/compute/aws-batch/stack.py, modules/compute/aws-batch/tests/test_app.py, modules/compute/aws-batch/tests/test_exportdata.py, modules/compute/aws-batch/tests/test_stack.py
Refactored and Unit tests for AWS Batch module
=> refactored and unit-tests for AWS Batch module

CHANGELOG.md, modules/dummy/blank/deployspec.yaml, modules/dummy/blank/export_metadata.py
Added output to demonstrate metadata usage in dummy/blank module....
=> adding dummy module output example

data/mwaa/requirements/requirements-emr-serverless.txt
Updating / adding emr-serverless requirements flle support for mwaa
=> adding emr-serverless requirements support

CHANGELOG.md, modules/compute/aws-batch/app.py, modules/compute/aws-batch/stack.py, modules/compute/emr-serverless/app.py, modules/orchestration/mwaa/README.md, modules/orchestration/mwaa/app.py, modules/orchestration/mwaa/deployspec.yaml, modules/orchestration/mwaa/plugins/s3_metadata_plugin.py, modules/orchestration/mwaa/stack.py, modules/storage/opensearch/app.py
Syncing the changes made to modules based off security scanning
=> syncing modules based off security scan work

modules/compute/aws-batch/app.py, modules/compute/aws-batch/stack.py, modules/compute/aws-batch/tests/test_app.py, modules/compute/aws-batch/tests/test_stack.py
imdsv2 and license-header changes to aws-batch
=> imdsv2 and license-header changes to aws-batch

modules/compute/eks/app.py, modules/compute/eks/helpers.py, modules/compute/eks/requirements.txt, modules/compute/eks/stack.py, modules/compute/eks/tests/conftest.py, modules/compute/eks/tests/test_app.py, modules/compute/eks/tests/test_helpers.py, modules/compute/eks/tests/test_stack.py
license-headers change to eks module
=> license-headers change to eks module

modules/database/neptune/app.py, modules/database/neptune/stack.py, modules/database/neptune/tests/test_app.py, modules/database/neptune/tests/test_stack.py
license-header changes and exception handling
=> license-header changes and exception handling

modules/ml/sagemaker-studio/app.py, modules/ml/sagemaker-studio/functions/sm_studio/enable_sm_projects/index.py, modules/ml/sagemaker-studio/helper_constructs/sm_roles.py, modules/ml/sagemaker-studio/scripts/check_lcc_state.sh, modules/ml/sagemaker-studio/scripts/delete-domains.py, modules/ml/sagemaker-studio/scripts/delete_efs.py, modules/ml/sagemaker-studio/scripts/on-jupyter-server-start.sh, modules/ml/sagemaker-studio/stack.py, modules/ml/sagemaker-studio/tests/test_app.py, modules/ml/sagemaker-studio/tests/test_stack.py
licene-headers change on ml/sagemaker-studio
=> licene-headers change on ml/sagemaker-studio

modules/orchestration/mwaa/app.py, modules/orchestration/mwaa/stack.py, modules/orchestration/mwaa/tests/test_app.py, modules/orchestration/mwaa/tests/test_stack.py
=> license headers for mwaa

modules/replication/dockerimage-replication/delete-repos.py, modules/replication/dockerimage-replication/get-list-of-eks-images.py, modules/replication/dockerimage-replication/helmparser/arguments.py, modules/replication/dockerimage-replication/helmparser/helm/commands.py, modules/replication/dockerimage-replication/helmparser/logging.py, modules/replication/dockerimage-replication/helmparser/parser/parser.py, modules/replication/dockerimage-replication/helmparser/utils/utils.py, modules/replication/dockerimage-replication/replication.sh, modules/replication/dockerimage-replication/tests/test_arguments.py, modules/replication/dockerimage-replication/tests/test_commands.py, modules/replication/dockerimage-replication/tests/test_parser.py, modules/replication/dockerimage-replication/tests/test_utils.py
images-rep sync - license headers
=> images-rep sync - license headers

modules/storage/efs/app.py, modules/storage/efs/stack.py, modules/storage/efs/tests/test_app.py, modules/storage/efs/tests/test_stack.py
efs license headers and exception handling
=> efs license headers and exception handling

modules/storage/fsx-lustre/app.py, modules/storage/fsx-lustre/stack.py, modules/storage/fsx-lustre/tests/test_app.py, modules/storage/fsx-lustre/tests/test_stack.py
=> license headers change on fsx

modules/storage/opensearch/app.py, modules/storage/opensearch/stack.py, modules/storage/opensearch/tests/test_app.py, modules/storage/opensearch/tests/test_stack.py
enabled logging on os and changed license-headers
=> enabled logging on os and changed license-headers

modules/network/basic-cdk/modulestack.template, modules/storage/buckets/modulestack.template, modules/storage/efs/modulestack.template
fixed the naming schema for cookie cutter description of iam policy names
=> fixed the naming schema

CHANGELOG.md, modules/service-catalog/app-registry/stack.py
integrated app insights with app registry
=> integrated app insights with app registry

CHANGELOG.md, data/mwaa/requirements/requirements-emr-serverless.txt, modules/orchestration/mwaa/requirements/requirements-emr.txt, modules/orchestration/mwaa/requirements/requirements-rosbag.txt, modules/orchestration/mwaa/requirements/requirements.txt
Fixing pillow versions due to security issues...Issues #20 thru #27
=> updating pillow version

CHANGELOG.md
Forgot change log from PR that updates solution info for stacks
=> adding changelog from previous pr

modules/compute/emr-serverless/stack.py
Force emr-application to auto-start and auto-stop
=> have emr-serverless app auto-start and auto-stop

CHANGELOG.md, modules/storage/buckets/stack.py
added ability for artifact buckets to write events to event bridge.
=> added ability for artifact buckets to write events to event bridge.

modules/storage/buckets/stack.py
fixed cdk nag issue on buckets module
=> fixed cdk nag issue on buckets module

modules/compute/aws-batch/stack.py
made the launch template name dynamic to allow multiple instances of batch module deployment
=> chore: batch module launch template name

CHANGELOG.md, manifests/local/compute-modules.yaml, modules/compute/eks/README.md, modules/compute/eks/stack.py
added support for S3 CSI Driver
=> added support for S3 CSI Driver

seedfarmer.yaml
=> updating seedfarmer yaml

manifests/local-isolated/containers-modules.yaml, manifests/local-isolated/deployment.yaml, manifests/local-isolated/ml-modules.yaml, modules/containers/ecr/README.md, modules/containers/ecr/app.py, modules/containers/ecr/coverage.ini, modules/containers/ecr/deployspec.yaml, modules/containers/ecr/modulestack.yaml, modules/containers/ecr/pyproject.toml, modules/containers/ecr/requirements.txt, modules/containers/ecr/setup.cfg, modules/containers/ecr/stack.py, modules/containers/ecr/tests/test_app.py, modules/containers/ecr/tests/test_stack.py
=> add ecr module

modules/containers/ecr/integ/integ_ecr.py, modules/containers/ecr/requirements.txt, modules/containers/ecr/setup.cfg, modules/containers/ecr/stack.py
- Adds integration test for ECR module.
- Adds `removal_policy` parameter to `ECRStack()` construct.
=> feat: adding integration tests for ecr module

CHANGELOG.md, modules/compute/eks/app.py
Added EKS outputs for feeding AWS Stepfunctions EKS Tasks
=> chore: Added EKS outputs for feeding AWS Stepfunctions EKS Tasks

CHANGELOG.md, modules/orchestration/mwaa/requirements/requirements-emr.txt, modules/orchestration/mwaa/requirements/requirements-rosbag.txt, modules/orchestration/mwaa/requirements/requirements.txt
removed conflicting boto3 version from mwaa reqs
=> chore: removed conflicting boto3 version from mwaa reqs

CHANGELOG.md, modules/database/rds/app.py, modules/database/rds/stack.py, modules/database/rds/tests/test_stack.py
- Made the CDK nags run as part of the unit testing
- Fixed some of the missing nag suppressions
=> chore: Fix CDK nags in rds module

CHANGELOG.md, modules/storage/ecr/README.md, modules/storage/ecr/app.py, modules/storage/ecr/stack.py, modules/storage/ecr/tests/test_app.py, modules/storage/ecr/tests/test_stack.py
#142
Add support to make ecr module removal policy configurable
=> adding ability to change ecr removal policy

CHANGELOG.md, data/mwaa/requirements/requirements-emr-serverless.txt, modules/orchestration/mwaa/requirements/requirements-emr.txt, modules/orchestration/mwaa/requirements/requirements-rosbag.txt, modules/orchestration/mwaa/requirements/requirements.txt
set Pillow version to 10.2.0 as per bot recommendation
=> set Pillow version to 10.2.0 as per bot recommendation

CHANGELOG.md, data/eks_dockerimage-replication/versions/1.29.yaml, manifests/local/compute-modules.yaml, modules/compute/eks/stack.py
Fixes #150 
added support for AWS CloudWatch Observability Managed Addon
=> added support for AWS CloudWatch Observability Managed Addon

CHANGELOG.md, modules/compute/eks/README.md, modules/compute/eks/app.py, modules/compute/eks/deployspec.yaml, modules/compute/eks/stack.py
cleaned up CNI metrics as its no longer used
=> cleaned up CNI metrics as its no longer used

CHANGELOG.md, modules/compute/eks/README.md
=> readme fixes

CHANGELOG.md, data/mwaa/requirements/requirements-emr-serverless.txt, modules/orchestration/mwaa/requirements/requirements-emr.txt, modules/orchestration/mwaa/requirements/requirements-rosbag.txt, modules/orchestration/mwaa/requirements/requirements.txt
set Pillow version to 10.3.0 as per bot recommendation
=> set Pillow version to 10.3.0 as per bot recommendation

README.md
Closes #164 
- Update README with hyperlinks to industy-specific repositories
=> chore: Add hyperlinks to industy-specific repositories

CHANGELOG.md, modules/network/basic-cdk/deployspec.yaml, modules/network/basic-cdk/requirements.in, modules/network/basic-cdk/requirements.txt, modules/network/basic-cdk/stack.py
- added support for bedrock endpoints
- bumped cdk versions on networking module
=> added support for bedrock endpoints

CHANGELOG.md, data/eks_dockerimage-replication/versions/1.29.yaml, data/eks_dockerimage-replication/versions/default.yaml, modules/compute/eks/README.md, modules/compute/eks/app.py, modules/compute/eks/stack.py
- refactored eks module the growing monolith stack
- fixed the breaking nginx ingress controller
- removed needless and extra permissions which are no longer needed
=> chore: refactored eks module

CHANGELOG.md, modules/compute/eks/README.md, modules/compute/eks/docs/eks-localzones/eks-lz-eksmanifest.yaml, modules/compute/eks/docs/eks-localzones/eks-lz.md, modules/compute/eks/docs/eks-private/eks-private-eksmanifest.yaml, modules/compute/eks/stack.py
Fixes #199 
added support for EKS Self Managed node groups with autoscaling
=> added support for EKS Self Managed node groups with autoscaling

CHANGELOG.md, modules/compute/aws-batch/requirements.in, modules/compute/aws-batch/requirements.txt, modules/compute/emr-serverless/requirements.in, modules/compute/emr-serverless/requirements.txt, modules/database/neptune/requirements.in, modules/database/neptune/requirements.txt, modules/dummy/blank/requirements.in, modules/dummy/blank/requirements.txt, modules/orchestration/mwaa/requirements.in, modules/orchestration/mwaa/requirements.txt, modules/service-catalog/app-registry/requirements.in, modules/service-catalog/app-registry/requirements.txt, modules/storage/buckets/requirements.in, modules/storage/buckets/requirements.txt, modules/storage/opensearch/requirements.in, modules/storage/opensearch/requirements.txt
fixed urlib3 version as per dependabot alert
=> fixed urlib3 version as per dependabot alert

scripts/generate-module-metadata.py
- changing module metadata path to partition by module name not version
=> chore: changing module metadata path to partition by module name not version

CHANGELOG.md, requirements.txt
=> bumped seedfarmer version

CHANGELOG.md, modules/compute/aws-batch/app.py, modules/compute/aws-batch/modulestack.yaml, modules/compute/aws-batch/stack.py, modules/compute/aws-batch/tests/test_app.py, modules/compute/aws-batch/tests/test_stack.py, modules/compute/eks/addons-iam-policies/ebs-csi-iam.json, modules/compute/eks/addons-iam-policies/fsx-csi-iam.json, modules/compute/eks/addons-iam-policies/ingress-controller.json, modules/compute/eks/app.py, modules/compute/eks/deployspec.yaml, modules/compute/eks/modulestack.yaml, modules/compute/eks/stack.py, modules/compute/eks/tests/test_app.py, modules/compute/eks/tests/test_stack.py, modules/compute/emr-on-eks/app.py, modules/compute/emr-on-eks/deployspec.yaml, modules/compute/emr-on-eks/emr_eks.py, modules/compute/emr-on-eks/modulestack.yaml, modules/compute/emr-on-eks/rbac_stack.py, modules/compute/emr-on-eks/tests/test_app.py, modules/compute/emr-on-eks/tests/test_stack.py, modules/storage/buckets/app.py, modules/storage/buckets/stack.py, modules/storage/buckets/tests/test_app.py, modules/storage/buckets/tests/test_stack.py
Fixes #208 
added partition support for local zone poc modules
=> added partition support for local zone poc modules

CHANGELOG.md, data/eks_dockerimage-replication/versions/1.29.yaml, data/eks_dockerimage-replication/versions/default.yaml, modules/compute/eks/README.md, modules/compute/eks/docs/eks-isolated/eks-isolated-docker-replication.yaml, modules/compute/eks/docs/eks-isolated/eks-isolated-eksmanifest.yaml, modules/compute/eks/docs/eks-localzones/eks-lz-manifest.yaml, modules/compute/eks/docs/eks-localzones/eks-lz.md, modules/compute/eks/docs/eks-private/eks-private-manifest.yaml, modules/compute/eks/docs/eks-private/eks-private.md, modules/compute/eks/stack.py
Fixes #211 
added support for nvidia device plugin for management of GPUs on EKS
=> added support for nvidia device plugin for management of GPUs on EKS

CHANGELOG.md, modules/storage/ecr/integ/integ_ecr.py
- fixed params in ecr integration test stack
=> chore: fix ecr integration test

CHANGELOG.md, modules/storage/opensearch-serverless/integ/integ_os_serverless.py, modules/storage/opensearch-serverless/requirements.in, modules/storage/opensearch-serverless/requirements.txt
- Closes #229 
- Adds integration testing for module `storage/opensearch-serverless`
=> chore: add integration tests for opensearch-serverless module

CHANGELOG.md, modules/compute/aws-batch/integ/integ_aws_batch.py, modules/compute/aws-batch/pyproject.toml, modules/compute/aws-batch/requirements.in, modules/compute/aws-batch/requirements.txt
Closes #217 
- add integration testing for module `compute/aws-batch`
=> chore: add integration testing for module `compute/aws-batch`

CHANGELOG.md, modules/compute/eks/README.md, modules/compute/eks/deployspec.yaml, modules/compute/eks/stack.py, modules/compute/eks/utils/iam.py
Fixes #278 
enable eks cluster to deploy to china region
=> enable eks cluster to deploy to china region

modules/compute/eks/stack.py, scripts/generate-module-metadata.py
https://github.com/awslabs/autonomous-driving-data-framework/issues/575
- Fix local variable assignment when `None`
- `ruff format`
=> fix: eks module syntax bug

data/eks_dockerimage-replication/versions/1.29.yaml
=> fix: update nvidia tag for images with a 'v' prefix

CHANGELOG.md, modules/integration/fsx-lustre-on-eks/README.md, modules/integration/fsx-lustre-on-eks/app.py, modules/integration/fsx-lustre-on-eks/stack_fsx_eks.py, modules/integration/fsx-lustre-on-eks/tests/test_stack.py
*Issue #, if available:* https://github.com/awslabs/idf-modules/issues/290
- fix `fsx-lustre-on-eks` to support non-public endpoints
=> fix `fsx-lustre-on-eks` to support non-public endpoints

CHANGELOG.md, modules/compute/eks/helpers.py, modules/compute/eks/stack.py
Allow EKS to override charts if available
=> adding support for chart overrides
