awslabs/idf-modules

CHANGELOG.md
modules/storage/buckets/stack.py

the hashlib.sha1 creation was modified to include `usedforsecurity=False` when creating the unique bucket names

syncing the solutions work for buckets

---

CHANGELOG.md
data/mwaa/requirements/requirements-emr-serverless.txt

The file `data/mwaa/requirements/requirements-emr-serverless.txt` was updated with Pillow~=9.2.0 as per dependabot request

updating Pillow lib in emr-serverless requirments for mwaa data file

---

CHANGELOG.md
data/mwaa/requirements/requirements-emr-serverless.txt

Update Pillow~=9.3.0 for emr-serverless-requirements in mwaa data file

updating pillow=9.3.0

---

CHANGELOG.md
data/mwaa/requirements/requirements-emr-serverless.txt

updated reqs.txt for emr-serverless module to support mwaa 2.6.3

updated reqs.txt for emr-serverless module to support mwaa 2.6.3

---

modules/compute/emr-serverless/deployspec.yaml
modules/compute/emr-serverless/modulestack.yaml

Trying to destroy an EMR-Serverless that has started applications prevents deletion.  Adding code to stop the started application on this cluster for deletion.

forcing app to stop in emr-s prior to deletion

---

CHANGELOG.md
modules/service-catalog/app-registry/register-stacks.py

added paginatior for CFN list stacks to scrape the stacks starting with addf

added paginatior for CFN list stacks to scrape the stacks starting with addf

---

CHANGELOG.md
modules/storage/fsx-lustre/app.py
modules/storage/fsx-lustre/tests/test_app.py

#93 
If a manifest passes in a relative import or export path that is missing a leading `/`, we will add it

add logic to validate relative paths

---

CHANGELOG.md
modules/compute/eks/README.md
modules/compute/eks/app.py
modules/compute/eks/stack.py

- DCV module requires to use IMDS service to determine whether it is a EC2 instance. It is recommended to use IMDSv2 for all ec2 instances. This CR makes IMDSv2 required in all nodes launched by eks.
- Use a designated role for all the nodes. Without this PR, all the nodes created by eks will have a randomly generated role. This CRs makes all the nodes to share the same Role. When we launch the DCV, we will add the permission to access DCV licenses in s3. The permission to access licenses will be added to this role.
- Also validated and fix formatting. Adding required output to README.md and CHANGELOG.md
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Add EKS Node Role and upgrade IMDS to vAdd EKS Node Role and upgrade IMDS to v2

---

modules/network/basic-cdk/integ/integ_network.py
modules/network/basic-cdk/requirements.txt
modules/network/basic-cdk/setup.cfg

Adding integration tests for idf module `network/basic-cdk`
- Test Cases
- _Network Accessible_
- _Network Not Accessible_
Run locally successfully
```shell
Running in parallel across regions: us-east-1, us-east-2, us-west-2
Running test /Users/hansonlu/work/awslabs/code/idf-modules/modules/network/basic-cdk/integ/integ_network.py in us-east-1
SUCCESS    integ/integ_network-Integration Tests Buckets Module/DefaultTest 771.749s
NO ASSERTIONS
Test Results:
Tests:    1 passed, 1 total
```
Run again in workflow below

chore: Add integration tests for network basic-cdk module

---

CHANGELOG.md
modules/replication/dockerimage-replication/deployspec.yaml
modules/replication/dockerimage-replication/replication.sh

The current replication module doesn't take into account if a repository already exists and always just invokes docker pull. This causes the module to get to a stuck state when hitting the docker API rate limits. 
Additionally, in some of the scripts we invoke create APIs for ECR or S3 and then immediately try to access those resources resulting in a "resource does not exist" exception. Adding sleep time after create API calls to allow resource creation time.
Adding a lookup to see if the image has already been replicated to ECR. If yes, it skips replication.

[Feature Improvement] Replication Module Improvements (Rate Limits & Race Conditions)

---

CHANGELOG.md
modules/orchestration/mwaa/app.py
modules/orchestration/mwaa/deployspec.yaml
modules/orchestration/mwaa/stack.py

#124 
Move the creation of the plugins.zip from app.py to deployspec b/c python 3.11.6 has an issue with shutil.  This is now done in deployspec via commandline 

removing shutil support for creating zip

---

CHANGELOG.md
manifests/local/database-modules.yaml
modules/database/rds/README.md
modules/database/rds/app.py
modules/database/rds/tests/test_stack.py

I'm updating the instance type for the MySQL DB after getting this message from AWS:
> Starting March 11, 2024, Amazon RDS will begin disabling the creation of Amazon RDS for MySQL, MariaDB, and PostgreSQL database instances running on M4, R4, or T2 instance types. 

chore: Update instance type for RDS module

---

CHANGELOG.md
manifests/local-isolated/containers-modules.yaml
modules/storage/ecr/README.md
modules/storage/ecr/app.py
modules/storage/ecr/stack.py
modules/storage/ecr/tests/test_stack.py

added image scan on push and KMS encryption to ECR module

feat: ecr - enable scan on push and KMS encryption

---

CHANGELOG.md
modules/compute/eks/app.py

exporting `kubectl handler iam role` for running kubectl calls from the downstream modules

chore: exporting kubectl handler iam role

---

CHANGELOG.md
data/eks_dockerimage-replication/versions/1.29.yaml
modules/compute/eks/stack.py

Fixes #165 
- upgraded `vpc-cni` version to `1.18.0` to support EKS 1.29 version
- This PR also fixed crashing `aws-node-agent` pod

bumping vpc cni version

---

CHANGELOG.md
modules/storage/ecr/stack.py

- Integration Testing Refactoring 
set `auto_delete_images` to `True` when removal policy is **DESTROY**

chore: set `auto_delete_images` to `True` when removal policy is **DESTROY**

---

.github/workflows/generate-module-metadata.yml
scripts/generate-module-metadata.py

**POC**
This is just a starting point at the moment.
- Triggered upon a release tag
- For now can be used with workflow dispatch as a test. It is available in my [fork](https://github.com/malachi-constant/idf-modules/actions/workflows/generate-module-metadata.yml)
- Figure out what metadata needs to be present besides `name`, `readme`, `source_url`, `gitpath`, `version`
- Publishing to S3 via the Action.
- Static Site setup using the published metadata as an index.

feat: Add generate module metadata action

---

.github/workflows/check-integration-tests.yml

chore: add random wait to integ workflow to avoid rate limit

---

CHANGELOG.md
modules/compute/emr-on-eks/README.md
modules/compute/emr-on-eks/deployspec.yaml
modules/compute/emr-serverless/README.md
modules/compute/emr-serverless/app.py

Fixes #215 
- refactored the deployspec of `emr-on-eks` module and used seedfarmer to add/group metadata of 2 stacks
- fixed the readme and app.py of `emr-serverless` module

refactored emreks and emr-serverless modules

---

.github/workflows/check-integration-tests.yml

- update workflow to only run once a day to avoid intermittent rate limit issues with our other repos

chore: update workflow to only run once a day 

---

CHANGELOG.md
manifests/local/compute-modules.yaml
modules/compute/eks/README.md
modules/compute/eks/stack.py
modules/compute/eks/tests/test_app.py
modules/compute/eks/tests/test_stack.py

Fixes #193 
- added support for whitelisting custom CIDRs from SSM Parameters and auto load AWS Codebuild IPs for being able to run seedfarmer commands. Attached a screenshot for reference.
- This improves the security posture of EKS API endpoint such that, nodes communicate privately and any communication to the EKS APIs will be allowed from whitelisted customer CIDRs and AWS CODEBUILD IPs (for being able to run seedfarmer commands outside of VPC)

feat: added support for whitelisting custom CIDRs from SSM Parameters

---

.github/workflows/check-integration-tests.yml

- Closes #230 
- Exempts module `blank/dummy` from integration tests check workflow

chore: exempt dummy module from integration check workflow

---

.github/workflows/module-checks-dev-requirements-change.yml
CHANGELOG.md

- updated `get-modules` workflow to only run tests against changed files in `modules/**`
- adds workflow specific to changes for `requirements-dev.txt` so all static checks are run

chore: update module checks workflow

---

CHANGELOG.md
modules/compute/eks/stack.py

[L149](https://github.com/awslabs/idf-modules/blob/dca0f5c68b2bbe1bcb10727cb14b5c9271bf2cd8/modules/compute/eks/stack.py#L149) refers to unassigned local variable `secrets_key`.
```
File "/codebuild/output/src2320534162/src/bundle/module/app.py", line 57, in <module>
--
620 | stack = Eks(
621 | ^^^^
622 | File "/root/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
623 | inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
624 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
625 | File "/codebuild/output/src2320534162/src/bundle/module/stack.py", line 149, in __init__
626 | secrets_key=secrets_key,
627 | ^^^^^^^^^^^
628 | UnboundLocalError: cannot access local variable 'secrets_key' where it is not …
```

fixed unbound secrets key in eks module

---

.github/workflows/module-checks.yml
modules/integration/fsx-lustre-on-eks/stack_fsx_eks.py
modules/integration/fsx-lustre-on-eks/tests/test_app.py
modules/integration/fsx-lustre-on-eks/tests/test_stack.py
modules/storage/fsx-lustre/stack.py

*Issue #, if available:* N/A, regression from #266
*Description of changes:* Ensure tests for *all* changed modules run, not just the first one.
`$ALL_CHANGED_FILES` contains a space-separated list of changed files, when piped into `cut` this resulted in only returning the results of the first changed file.

Run CI on all changed modules, not just the first one.

---

.github/workflows/check-integration-tests.yml
CHANGELOG.md

- pin external gh actions to hash

chore: pin external gh actions to hash

---

CHANGELOG.md
data/eks_dockerimage-replication/versions/1.29.yaml
modules/compute/eks/stack.py

- bump grafana, kyverno, prometheus, and cert manager chart versions
- fix s3 csi addon
avoids below issues with outdated charts
```
<REDACTED> | 3:59:36 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | cluster/chart-prometheus-chart/Resource/Default (clusterchartprometheuschartF4492F33) Received response status [FAILED] from custom resource. Message returned: Error: b'Release "prometheus-for-amp" does not exist. Installing it now.\nError: 5 errors occurred:\n\t* Internal error occurred: failed calling webhook "mservice.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s": no endpoints available for service "aws-load-balancer-webhook-service"\n\t* Internal …
```

chore: bump chart versions & fix s3 csi addon

---

CHANGELOG.md
modules/compute/eks/stack.py

*Issue, if available:*
```
[Container] 2025/03/07 22:50:50.210655 Running command if [ -n "$SEEDFARMER_PARAMETER_EKS_ADMIN_ROLE_NAME" ] ; then
...
Error: describing cluster versions: operation error EKS: DescribeClusterVersions, https response 
error StatusCode: 403, RequestID: 7e7cf37e-3a92-409e-92b1-58fd38fe5499, api error 
AccessDeniedException: User: arn:aws:sts::<REDACTED>:assumed-role/addf-eks-viz-core-
eks-us-west-2-masterrole/aws-auth-ops is not authorized to perform: eks:DescribeClusterVersions
on resource: arn:aws:eks:us-west-2:<REDACTED:*
```
Adding missing eks:DescribeClusterVersions permission to eks cluster admin role
*Testing:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

fix: add eks:DescribeClusterVersions
